#!/usr/bin/env python3
"""Pack a recorded Space Impact game for the Game Boy's benchmark ROM.

Usage: si_bench.py GOLDEN_DIR OUT_DIR

Reads GOLDEN_DIR/events.txt ("EVENT A B KEYS" in hex, tools/si_events.py)
and the seed from GOLDEN_DIR/setup.txt, and writes OUT_DIR/si_bench.h and
OUT_DIR/si_bench_N.c, one array per bank of 16000 bytes, of a stream of:

  0x00-0x3f     that many plus one ticks (event 0, a 0)
  0x40-0x4f     a key down, the key's code in the low bits
  0x60-0x6f     a key up
  0x80 lo hi    the keys held from here on
  0xc0 ev a     any other event
  0xff a        the autopilot's lives, a
  0xfe          the end

platform/gb/main.c (SI_BENCH) plays it as platform/host/si_replay_main.c
plays the events: the game is the host's, frame for frame.
"""
import sys
from pathlib import Path

CHUNK = 16000


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    golden, out = Path(sys.argv[1]), Path(sys.argv[2])
    seed = int((golden / "setup.txt").read_text().split()[0], 16)
    events = [tuple(int(x, 16) for x in line.split()) for line in (golden / "events.txt").read_text().splitlines()
              if line.strip()]
    stream, keys, run = bytearray(), None, 0

    def flush():
        nonlocal run
        while run:
            n = min(run, 64)
            stream.append(n - 1)
            run -= n

    for event, a, _b, held in events:
        if event != 0xFF and held != keys:
            flush()
            stream.extend([0x80, held & 0xFF, held >> 8])
            keys = held
        if event == 0 and a == 0:
            run += 1
            continue
        flush()
        if event == 1 and a < 16:
            stream.append(0x40 | a)
        elif event == 2 and a < 16:
            stream.append(0x60 | a)
        elif event == 0xFF:
            stream.extend([0xFF, a & 0xFF])
        else:
            stream.extend([0xC0, event, a])
    flush()
    stream.append(0xFE)

    out.mkdir(parents=True, exist_ok=True)
    chunks = [stream[i:i + CHUNK] for i in range(0, len(stream), CHUNK)]
    header = [
        "/* Generated by tools/si_bench.py from a recorded game. Do not commit. */",
        "#ifndef SI_BENCH_H", "#define SI_BENCH_H", "", "#include <stdint.h>", "",
        f"#define SI_BENCH_SEED 0x{seed:08x}ul",
        f"#define SI_BENCH_CHUNKS {len(chunks)}",
        f"#define SI_BENCH_CHUNK {CHUNK}",
        f"#define SI_BENCH_EVENTS {len(events)}",
    ]
    for i, chunk in enumerate(chunks):
        header.append(f"extern const uint8_t si_bench_{i}[{len(chunk)}];")
        lines = [f'#include "si_bench.h"', "", f"const uint8_t si_bench_{i}[{len(chunk)}] = {{"]
        lines += ["    " + ", ".join(f"0x{b:02x}" for b in chunk[j:j + 16]) + "," for j in range(0, len(chunk), 16)]
        (out / f"si_bench_{i}.c").write_text("\n".join(lines + ["};", ""]))
    header.append("#define SI_BENCH_LIST " + ", ".join(f"si_bench_{i}" for i in range(len(chunks))))
    (out / "si_bench.h").write_text("\n".join(header + ["", "#endif", ""]))
    print(f"{len(events)} events, {len(stream)} bytes in {len(chunks)} banks")


if __name__ == "__main__":
    main()
