#!/usr/bin/env python3
"""Extract the 3210 v6.00 game graphics from your own dump into C arrays.

Usage: extract_assets.py DUMP OUT_DIR

DUMP is either the raw flash file (3210f600a.fls) or the 16-bit byte-swapped
image the static tools use (3210f600a_swap16.bin); it is identified by hash.
Writes OUT_DIR/game_assets.c and OUT_DIR/game_assets.h. The output is derived
from the firmware and must stay in an ignored directory.
"""
import hashlib
import sys
from pathlib import Path

FLASH_BASE = 0x200000
SHA256_RAW = "7bf29b96e544b682c4d6d01c7a6eaef89909c4191a52d829115d37b31c0c0d8a"
SHA256_SWAP16 = "66d2ec57385099d6dca8d93b75d72fcde496f3f8a3246331351d8ebce6fac8c1"

# (name, address, size in bytes, description). Addresses are NSE-8/9 v6.00
# only. Bitmaps are column-major, bit (y & 7) of each byte is row y.
TABLES = [
    ("game_tile_bitmaps", 0x2D94BC, 74 * 7, "7x7 tiles, 7 bytes each: blank + 0x49 symbols"),
    ("game_tile_back", 0x2D96C4, 8, "card back, 7x7 plus a pad byte"),
    ("game_tile_cursor", 0x2D96CC, 8, "cursor frame, 7x7 plus a pad byte"),
    ("games_digit_glyphs", 0x2D96EC, 10 * 3, "3x5 digits 0..9, 3 bytes each"),
    ("game_speed_table", 0x2D9738, 9, "Snake speed per level, units of 10 ms"),
    ("snake_food_bitmap", 0x2D9744, 4, "4x4"),
    ("game3_background", 0x2D9764, 504, "84x48 scene, 6 bytes per column"),
    ("game3_sprites", 0x2D995C, 0x2D9A20 - 0x2D995C, "10x10 sprites, 20 bytes each, then smaller pieces"),
]


def load_image(path):
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest == SHA256_RAW:
        return data
    if digest == SHA256_SWAP16:
        # Byte tables are in address order in the raw file; undo the swap.
        out = bytearray(data)
        out[0::2], out[1::2] = data[1::2], data[0::2]
        return bytes(out)
    sys.exit(
        f"{path}: sha256 {digest} is not the NSE-8/9 v6.00 dump "
        f"(expected {SHA256_RAW} or its swap16 form {SHA256_SWAP16})"
    )


def c_array(name, data):
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        lines.append("    " + " ".join(f"0x{b:02x}," for b in data[i:i + 12]))
    lines.append("};")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    image = load_image(Path(sys.argv[1]))
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    banner = "/* Generated by tools/extract_assets.py from a firmware dump. Do not commit. */"
    header = [banner, "#ifndef GAME_ASSETS_H", "#define GAME_ASSETS_H", "", "#include <stdint.h>", ""]
    source = [banner, '#include "game_assets.h"', ""]
    for name, addr, size, desc in TABLES:
        data = image[addr - FLASH_BASE:addr - FLASH_BASE + size]
        header.append(f"/* 0x{addr:06x}: {desc} */")
        header.append(f"extern const uint8_t {name}[{size}];")
        source.append(c_array(name, data))
        source.append("")
    header += ["", "#endif", ""]

    (out_dir / "game_assets.h").write_text("\n".join(header))
    (out_dir / "game_assets.c").write_text("\n".join(source))
    print(f"wrote {out_dir}/game_assets.c and game_assets.h ({len(TABLES)} tables)")


if __name__ == "__main__":
    main()
