#!/usr/bin/env python3
"""Extract the 3310 v6.39 Space Impact data from your own dump into C arrays.

Usage: extract_assets.py DUMP OUT_DIR

DUMP is the 2 MiB flash image `make dump` writes (3310f639e.fls), or the
16-bit byte-swapped form the static tools use; it is identified by hash.
Writes OUT_DIR/game_assets.c and OUT_DIR/game_assets.h. The output is derived
from the firmware and must stay in an ignored directory.

The game's data is one contiguous region of the image that refers to itself
by absolute address (sprite descriptors hold bitmap pointers, level headers
hold spawn list pointers). It is copied whole and the core reads it by
firmware address; see core/si_data.h and the map in the MAME fork's
docs/games_applications_3310.md.
"""
import hashlib
import sys
from pathlib import Path

FLASH_BASE = 0x200000
SHA256_RAW = "975ec791205f026d647254ee772d7fa32691fa50c72a68eecdaff7c8a5921442"

# Tilemaps, spawn lists, level headers, y paths, tiles, sprite bitmaps and
# descriptors, HUD icons and the object templates.
DATA_START, DATA_END = 0x311740, 0x313384
# Initialised-data images of tables the firmware keeps in RAM.
DIGIT_GLYPHS = (0x2F2320, 40)  # ten 4x5 digits, 4 bytes each
LEVEL_TABLE = (0x2F30D4, 8)  # pointers to the level headers
TYPE_FRAMES = (0x2F3108, 37)  # per object type, pointer to its sprite descriptors


def swap16(data):
    out = bytearray(data)
    out[0::2], out[1::2] = data[1::2], data[0::2]
    return bytes(out)


def load_image(path):
    data = path.read_bytes()
    if hashlib.sha256(data).hexdigest() == SHA256_RAW:
        return data
    if hashlib.sha256(swap16(data)).hexdigest() == SHA256_RAW:
        return swap16(data)
    sys.exit(f"{path} is not the NHM-5 v6.39 PPM E image (SHA-256 {SHA256_RAW})")


def c_bytes(name, data):
    lines = [f"const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 16):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def c_words(name, words):
    lines = [f"const uint32_t {name}[{len(words)}] = {{"]
    for i in range(0, len(words), 4):
        lines.append("    " + ", ".join(f"0x{w:06x}" for w in words[i:i + 4]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    image = load_image(Path(sys.argv[1]))
    out = Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)

    def at(addr, size):
        return image[addr - FLASH_BASE:addr - FLASH_BASE + size]

    def words(addr, count):
        return [int.from_bytes(at(addr + 4 * i, 4), "big") for i in range(count)]

    data = at(DATA_START, DATA_END - DATA_START)
    levels = words(*LEVEL_TABLE)
    frames = words(*TYPE_FRAMES)
    for pointer in levels + [f for f in frames if f]:
        if not DATA_START <= pointer < DATA_END:
            sys.exit(f"pointer {pointer:#x} is outside the copied region")

    header = f"""/* Generated by tools/extract_assets.py from the firmware dump. Do not commit. */
#ifndef GAME_ASSETS_H
#define GAME_ASSETS_H

#include <stdint.h>

#define SI_DATA_BASE 0x{DATA_START:06x}ul
#define SI_DATA_SIZE {len(data)}
#define SI_TYPE_COUNT {len(frames)}
#define SI_LEVEL_COUNT {len(levels)}

extern const uint8_t si_data[SI_DATA_SIZE];
extern const uint8_t si_digit_glyphs[{DIGIT_GLYPHS[1]}];
extern const uint32_t si_level_table[SI_LEVEL_COUNT];
extern const uint32_t si_type_frames[SI_TYPE_COUNT];

#endif
"""
    source = "\n\n".join([
        '/* Generated by tools/extract_assets.py from the firmware dump. Do not commit. */\n#include "game_assets.h"',
        c_bytes("si_data", data),
        c_bytes("si_digit_glyphs", at(*DIGIT_GLYPHS)),
        c_words("si_level_table", levels),
        c_words("si_type_frames", frames),
    ]) + "\n"
    (out / "game_assets.h").write_text(header)
    (out / "game_assets.c").write_text(source)
    print(f"wrote {out}/game_assets.c ({len(data)} bytes of game data)")


if __name__ == "__main__":
    main()
