#!/usr/bin/env python3
"""Turn assets/font12.txt (ASCII-art glyphs, 12 rows each) into a C font.

Usage: font12_to_c.py SHEET OUT_DIR

Writes OUT_DIR/font12.c and font12.h defining `font12` in the core's
`struct font` layout. Glyphs are trimmed to their ink and followed by a gap;
the digits share one cell width so numbers line up. The sheet's icons and
the kerning the original project applies are not used.
"""
import re
import sys
from pathlib import Path

HEIGHT, BASELINE = 12, 9
FIRST, LAST = 0x20, 0x7E
GAP, SPACE = 2, 5


def read_sheet(path):
    glyphs, code = {}, None
    for line in Path(path).read_text().splitlines():
        match = re.match(r"glyph 0x([0-9A-Fa-f]+)", line)
        if match:
            code = int(match.group(1), 16)
            glyphs[code] = []
        elif code is not None and re.fullmatch(r"[.#]+", line):
            glyphs[code].append(line)
    return glyphs


def columns(rows, left, right):
    return [sum(1 << y for y, row in enumerate(rows) if row[x] == "#") for x in range(left, right)]


def ink(rows):
    used = [x for x in range(len(rows[0])) if any(row[x] == "#" for row in rows)]
    return (used[0], used[-1] + 1) if used else (0, 0)


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    sheet = read_sheet(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    digit_ink = [ink(sheet[c]) for c in range(0x30, 0x3A)]
    digit_left, digit_right = min(l for l, _ in digit_ink), max(r for _, r in digit_ink)
    glyphs = []
    for code in range(FIRST, LAST + 1):
        rows = sheet[code]
        if len(rows) != HEIGHT:
            sys.exit(f"glyph 0x{code:02x} has {len(rows)} rows, expected {HEIGHT}")
        if code == 0x20:
            glyphs.append([0] * SPACE)
        elif 0x30 <= code <= 0x39:
            glyphs.append(columns(rows, digit_left, digit_right) + [0] * GAP)
        else:
            glyphs.append(columns(rows, *ink(rows)) + [0] * GAP)

    data = [c for glyph in glyphs for c in glyph]
    offsets, at = [], 0
    for glyph in glyphs:
        offsets.append(at)
        at += len(glyph)
    offsets.append(at)

    source = ["/* Generated by tools/font12_to_c.py from assets/font12.txt. */", '#include "font12.h"', ""]
    source.append(f"static const uint16_t font12_columns[{len(data)}] = {{")
    source += ["    " + " ".join(f"0x{c:04x}," for c in data[i:i + 10]) for i in range(0, len(data), 10)]
    source.append("};")
    source.append(f"static const uint16_t font12_offsets[{len(offsets)}] = {{")
    source += ["    " + " ".join(f"{o}," for o in offsets[i:i + 12]) for i in range(0, len(offsets), 12)]
    source.append("};")
    source.append(f"const struct font font12 = {{ {HEIGHT}, {BASELINE}, font12_offsets, font12_columns }};")
    source.append("")
    header = ["/* Generated by tools/font12_to_c.py from assets/font12.txt. */", "#ifndef FONT12_H", "#define FONT12_H",
              "", '#include "font.h"', "", "extern const struct font font12;", "", "#endif", ""]
    (out_dir / "font12.c").write_text("\n".join(source))
    (out_dir / "font12.h").write_text("\n".join(header))
    print(f"wrote {out_dir}/font12.c and font12.h")


if __name__ == "__main__":
    main()
